#ifndef _IOT_CONFIG_H
#define _IOT_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define AWS_IOT_MQTT_MAX_RECONNECT_WAIT_INTERVAL 128000
#define AWS_IOT_MQTT_MIN_RECONNECT_WAIT_INTERVAL 1000

#define AWS_IOT_MQTT_TX_BUF_LEN 512
#define AWS_IOT_MQTT_RX_BUF_LEN 512
#define MAX_SIZE_OF_THING_NAME 32
#define MAX_SIZE_OF_UNIQUE_CLIENT_ID_BYTES 64
#define MAX_ACKS_TO_COMEIN_AT_ANY_GIVEN_TIME 10 
#define MAX_JSON_TOKEN_EXPECTED 50
#define SHADOW_MAX_SIZE_OF_RX_BUFFER (AWS_IOT_MQTT_RX_BUF_LEN+1)
#define MAX_SHADOW_TOPIC_LENGTH_WITHOUT_THINGNAME 60
#define MAX_THINGNAME_HANDLED_AT_ANY_GIVEN_TIME 10
#define MAX_SIZE_OF_JOB_ID 16
#define  MAX_JOB_TOPIC_LENGTH_WITHOUT_JOB_ID_OR_THING_NAME  MAX_SIZE_OF_THING_NAME

#define MAX_SIZE_CLIENT_ID_WITH_SEQUENCE MAX_SIZE_OF_UNIQUE_CLIENT_ID_BYTES + 10
#define MAX_SIZE_CLIENT_TOKEN_CLIENT_SEQUENCE MAX_SIZE_CLIENT_ID_WITH_SEQUENCE + 20
#define AWS_IOT_MQTT_NUM_SUBSCRIBE_HANDLERS 8
#define MAX_SHADOW_TOPIC_LENGTH_BYTES MAX_SHADOW_TOPIC_LENGTH_WITHOUT_THINGNAME + MAX_SIZE_OF_THING_NAME
#define MAX_JOB_TOPIC_LENGTH_BYTES MAX_JOB_TOPIC_LENGTH_WITHOUT_JOB_ID_OR_THING_NAME + MAX_SIZE_OF_THING_NAME + MAX_SIZE_OF_JOB_ID + 2

#ifdef __cplusplus
}
#endif

#endif // _IOT_CONFIG_H

