#pragma once

#include <kernel/cdefs.h>
#include <bits/timer_base.h>

#define COP_CPROC_TE   0

#define COP_CPROC_TE_CRN_TIMER_0    0
#define COP_CPROC_TE_CRN_TIMER_1    1
#define COP_CPROC_TE_CRN_TIMER_2    2
#define COP_CPROC_TE_CRN_TIMER_3    3
#define COP_CPROC_TE_CRN_EVENT_TS0  4
#define COP_CPROC_TE_CRN_EVENT_TS1  5
#define COP_CPROC_TE_CRN_EVENT_TS2  6
#define COP_CPROC_TE_CRN_EVENT_TS3  7

#define COP_CPROC_TE_CRN_EVENT_MASK 8
#define COP_CPROC_TE_OPC1_EVENT_MASK_LO         0
#define COP_CPROC_TE_OPC1_EVENT_MASK_HI         1
#define COP_CPROC_TE_OPC1_EVENT_MASK_PENDING_LO 2
#define COP_CPROC_TE_OPC1_EVENT_MASK_PENDING_HI 3
#define COP_CPROC_TE_OPC1_EVENT_MASK_RAW_LO     4
#define COP_CPROC_TE_OPC1_EVENT_MASK_RAW_HI     5
#define COP_CPROC_TE_OPC1_EVENT_MASK_PENDING_ID 6

#define COP_CPROC_TE_CRN_EVENT_SET     9
#define COP_CPROC_TE_OPC1_EVENT_SET_LO 0
#define COP_CPROC_TE_OPC1_EVENT_SET_HI 1

#define COP_CPROC_TE_CRN_EVENT_CLR     10
#define COP_CPROC_TE_OPC1_EVENT_CLR_LO 0
#define COP_CPROC_TE_OPC1_EVENT_CLR_HI 1

#define COP_CPROC_TE_CRN_EVENT_WAIT    15
#define COP_CPROC_TE_OPC1_EVENT_WAIT_EVENT BIT(0)
#define COP_CPROC_TE_OPC1_EVENT_WAIT_TIMER BIT(1)
#define COP_CPROC_TE_OPC1_EVENT_WAIT_DMA   BIT(2)

#define COP_WAIT_EVENT COP_CPROC_TE_OPC1_EVENT_WAIT_EVENT
#define COP_WAIT_TIMER COP_CPROC_TE_OPC1_EVENT_WAIT_TIMER
#define COP_WAIT_DMA   COP_CPROC_TE_OPC1_EVENT_WAIT_DMA

#define COP_CPROC_DMA  1

#define COP_CPROC_DMA_CRN_EVENT   0
#define COP_CPROC_DMA_CRN_SIZE    1
#define COP_CPROC_DMA_CRN_ADDR    2
#define COP_CPROC_DMA_CRN_EV_MASK 3
#define COP_CPROC_DMA_CRN_DATA_8  4
#define COP_CPROC_DMA_CRN_DATA_32 5
#define COP_CPROC_DMA_CRN_TOTAL   6
#define COP_CPROC_DMA_CRN_FLUSH   7

#define COP_DMA_EVENT_IDLE  BIT(0)
#define COP_DMA_EVENT_RX_8  BIT(1)
#define COP_DMA_EVENT_TX_8  BIT(2)
#define COP_DMA_EVENT_RX_32 BIT(3)
#define COP_DMA_EVENT_TX_32 BIT(4)

#define COP_DMA_MODE_TX  0
#define COP_DMA_MODE_RX  BIT(1)
#define COP_DMA_MODE_CRC BIT(0)

#define COP_CPROC_CRC  2

#define COP_CPROC_CRC_CRN_POLY    0
#define COP_CPROC_CRC_CRN_CSUM    1
#define COP_CPROC_CRC_CRN_DATA_1  4
#define COP_CPROC_CRC_CRN_DATA_8  5
#define COP_CPROC_CRC_CRN_DATA_16 6
#define COP_CPROC_CRC_CRN_DATA_32 7

#define COP_CPROC_WDOG 3

#define COP_CPROC_WDOG_CRN_EN      0
#define COP_CPROC_WDOG_CRN_TIMEOUT 1
